<div class="col-lg-12 text-center">
<h2 class="section-heading">Contacts</h4>
<p class="large text-muted">Our Representatives</p>
</div>
<table class="table table-striped table-inverse table-bordered table-hover table-sm table-responsive">
<thead>
</thead>
<tbody>
        <?php foreach ($this->contacts as $contact): ?>
            <tr><td><?=$contact?></td></tr>
        <?php endforeach; ?>
</tbody>
</table>
