  <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand page-scroll" href="#page-top">Code Warriors</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="hidden">
            <a href="#page-top"></a>
          </li>
          <li>
            <a class="" href="index.php">Home</a>
          </li>
          <li>
            <a class="" href="customwebsites.php">Website</a>
          </li>
          <li>
            <a class="" href="consulting.php">Consulting</a>
          </li>
          <li>
            <a class="" href="reporting.php">Reporting</a>
          </li>
          <li>
            <a class="" href="seo.php">SEO</a>
          </li>
          <li>
            <a class="" href="applicationdev.php">App</a>
          </li>
          <li>
            <a class="" href="support.php">Support</a>
          </li>
          <li>
            <a class="" href="mobiledev.php">Mobile</a>
          </li>
          <li>
            <a class="" href="bpo.php">BPO</a>
          </li>
          <li>
            <a class="" href="training.php">Training</a>
          </li>
          <li>
            <a class="" href="webgamedev.php">Webgame</a>
          </li>
          <li>
            <a class="" href="pcgamedev.php">PCGame</a>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
    <section>
      <div class="container">
        <div class="row tpmg45">

          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Data Warehousing and Reports</h2>
            <h3 class="section-subheading text-muted">A picture says a thousand words</h3>
          </div>
        </div>

        <div class="row">
          <div class="col-md-5 col-sm-6 portfolio-item">
            <img src="images/reports.jpg" class="img-responsive" alt="project1">
          </div>
          <div class="col-md-4 col-sm-6 portfolio-item">
            <p>
              We offer high valued reports using latest technolgies. We have prepared reporting services for the biggest companies in the world including Microsoft, Apple, Google Tesla, Yahoo and LinkedIn. We use the latest standards and make sense of your information
              even though it may be huge.
            </p>
          </div>
          <a href="seo.php">Next >>>></a>

        </div>
      </div>
    </section>

